[package]
name = "bevy_quinnet"
version = "0.5.0"
description = "Bevy plugin for Client/Server multiplayer games using QUIC"
repository = "https://github.com/Henauxg/bevy_quinnet"
documentation = "https://docs.rs/bevy_quinnet"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "networking", "quic", "bevy", "plugin"]
categories = ["game-development", "network-programming"]
readme = "README.md"
exclude = ["assets/"]

[dependencies]
bevy = { path = "../bevy_am", default-features = false, features = [] }
rustls = { version = "0.21.0", default-features = false, features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.1"
ring = "0.16.20"
tokio = { version = "1.29.1", features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
rcgen = "0.11.0"
quinn = "0.10.1"
quinn-proto = "0.10.1"
futures-util = "0.3.24"
futures = "0.3.24"
bincode = "1.3.3"
serde = "1.0.145"
bytes = "1.4.0"
base64 = "0.13.1"
thiserror = "1.0.37"

[dev-dependencies]
bevy = { path = "../bevy_am", default-features = false, features = ["bevy_asset", "bevy_audio", "vorbis", "bevy_winit", "bevy_render", "bevy_sprite", "bevy_ui", "bevy_text", "bevy_core_pipeline"] }
rand = "0.8.5"

[[example]]
name = "breakout"
path = "examples/breakout/breakout.rs"

[[example]]
name = "chat-server"
path = "examples/chat/server.rs"

[[example]]
name = "chat-client"
path = "examples/chat/client.rs"
